# Generated by Django 6.0.4 on 2026-04-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pro_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pro_names', to='lectures.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lec_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lec_names', to='lectures.lecture'),
            preserve_default=False,
        ),
    ]
