# Generated by Django 6.0.4 on 2026-04-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_pro_name_student_lec_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lec_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lec_codes', to='lectures.lecture'),
            preserve_default=False,
        ),
    ]
