# Generated by Django 6.0.4 on 2026-04-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_student_lec_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lec_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lec_name',
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='lectures.lecture'),
            preserve_default=False,
        ),
    ]
