# Generated by Django 6.0.4 on 2026-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_remove_student_lecture_lecturestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lecture',
            field=models.ManyToManyField(related_name='students', through='lectures.LectureStudent', to='lectures.lecture'),
        ),
    ]
